# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('native_lang', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=200)),
                ('reason_to_move', models.TextField(max_length=200)),
                ('reason_to_reject', models.TextField(max_length=200)),
                ('applicant_score', models.TextField(max_length=200)),
                ('passport_no', models.TextField(max_length=200)),
                ('identification_doc', models.FileField(null=True, upload_to=main.models.getfilepath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
