# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identification_doc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='place',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
