# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170401_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_doc', models.FileField(upload_to=main.models.getfilepath)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UploadIdentification'),
        ),
    ]
