# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20170401_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='doc',
        ),
        migrations.AddField(
            model_name='uploadidentification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
